# Generated by Django 5.0.9 on 2024-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionContent',
            new_name='Content',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.RemoveField(
            model_name='tests',
            name='answers',
        ),
        migrations.AddField(
            model_name='tests',
            name='answer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Answer'),
        ),
    ]
